### ISSUE TITLE
Don't check binaries into source control

### ISSUE THREAD

**Issue by tonygilkerson** [claygilk/ThunderDome#4]
you don't want to check in the bin and obj file to github. You just want to check in your code and leave out the stuff that the compiler generates for you. The way to do this is create a `.gitignore` file and list all the stuff you want git to ignore :-)

**Comment by tonygilkerson** [comment]
This one is a little tricky.  You might need to delete your `bin` and `obj` folders and all the files contained within them, then commit and push this to Github.  Then add the `.gitignore` files. Or maybe accepting #5 will do the trick.  Let's see

**Comment by claygilk** [comment]
Alright. I think I resolved this issue. I added a .gitignore file. I just took the one that was pre-generated in my other git repos. That didn't seem to work though, so I manually removed the bin/ and obj/ directories then pushed again. I pushed one more time after running the program.cs to see if they would stay ignored and they did.
